### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by Juke34** [The-Sequence-Ontology/Specifications#5]
Within the paragraph  about **Column 3: "type"**
 There is a) and c) but b) is missing. I found the description made here http://gmod.org/wiki/GFF3 by Scott cain clearer.

**Comment by srynobio** [comment]
A better understanding of what is unclear would be helpful, as the two sources use the same description with additional clarification (spec version).

From the specification [page](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md)

`Column 3: "type"`
The type of the feature (previously called the "method"). This is constrained to be either: (a) a term from the "lite" version of the Sequence Ontology - SOFA, _a term from the full Sequence Ontology - it must be an is_a child of sequence_feature (SO:0000110)_ or (c) a SOFA or SO accession number. The latter alternative is distinguished using the syntax SO:000000.

From the GMOD page.

`Column 3: "type"`
The type of the feature (previously called the "method"). This is constrained to be either: (a) a term from the "lite" sequence ontology, SOFA; or (b) a SOFA accession number. The latter alternative is distinguished using the syntax SO:000000. This field is required.

**Comment by Juke34** [comment]
I meant I was disturbed by the sentence saying : 
Either (a).... , or (c)... <= I was thinking there are 3 alternatives and one is not explained.
Either (a)... , or (b) ... would be correct if I understand correctly. Otherwise I missed something.

**Comment by srynobio** [comment]
@Juke34 I see good point.

@alexhenrie do you want to make the changes to the GFF3 spec page?

**Comment by alexhenrie** [comment]
@srynobio I talked it over with @nicoleruiz and here's what we propose:

<dl>
<dt>Column 3: "type"</dt>
<dd>The type of the feature (previously called the "method"). This is constrained to be either a term from the Sequence Ontology or an SO accession number. The latter alternative is distinguished using the syntax SO:000000. In either case, it must be sequence_feature (SO:0000110) or an is_a child of it.</dd>
</dl>

There is no need to say "SO or SOFA" because SOFA is a perfect subset of SO. Also, our understanding is that the type can be simply "sequence_feature" and not a more specific child.

If you approve, I'll make this change. Should I also increment the version number and add a note to the changelog?

**Comment by srynobio** [comment]
Great thanks!

**Comment by alexhenrie** [comment]
Fixed by 0a257025c9b061621cc779f17aef9d0e4ae80b5e
